services:
  fastapi:
    build: .
    container_name: collec_AI
    ports:
      - "13131:13131"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./keys/collec-250523.json:/app/keys/collec-250523.json
      - ./data:/app/data 

    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
